### ISSUE TITLE
Rejzor

### ISSUE THREAD

**Issue by michaelKurowski** [michaelKurowski/lokim2#132]
The introduction will consist of:
 - Overall architecture
   - Network contract between frontend and backend
     - What do we have now
       - HTTP endpoints
       - Sessions and cookies
       - Upgrading to websockets
       - Authorization and websockets
      - What will come
        - HTTPS & WSS
        - Service Worker & PWA
           - Caching - magic that let you use app offline
           - Service Worker - micro-services inside your browser
 - Continous Integration
   - Docker images
     - MongoDB
     - LokIM server
   - CircleCI Cache
   - Cypress dependencies
   - Backend and Frontend dependencies installation
   - Static analysis
   - Backend UTs and ITs + Test coverage
   - Frontend UTs and ITs + Test coverage
   - Webpack bundling, and what's that about
     -  Bundle imports together
     - Uglyfying
     - Sourcemaps
   - E2E tests
     - Whole app
       - HTML Data atrribute
       - Cypress tests
       - Artifacts collection
     - Backend specific 
       - Mocha
    - Pipeline rebuilding to solve unstable tests
 - Git workflow 
   - Issues 
   - Docs => PR => Code review 
   - Semantic commit messages
 - Dev ops rules
   - Avoid OS restricted scripts
   - Scripts need to be testable

**Comment by michaelKurowski** [comment]
@MarcinGrzeszczak Please write down a brief docs of how sessions are being handled

**Comment by michaelKurowski** [comment]
@Rejzor FYI

**Comment by MarcinGrzeszczak** [comment]
# Sessions

## Dependencies 
* [Passport](http://www.passportjs.org)
* [Express-Session](https://github.com/expressjs/session)

## Endpoints
* [/login](https://github.com/michaelKurowski/lokim2/blob/master/src/server/routes/controllers/logInUser.js)
* [/logout](https://github.com/michaelKurowski/lokim2/blob/master/src/server/routes/controllers/logOutUser.js)

## Expected request 
* ### LogIn
   #### Headers: 
    * Content-type: application/json

   #### Payload: 
    * username : [String]
    * password : [String]
   #### Example
    ```
     {
           "username": "Dummy username",
           "password": "Dummy password"
     }
    ```
## Expected response 
### Headers
* Connection: keep-alive
* Content-Length
* Content-Type: application/json; charset=utf-8
* Date
* ETag
* X-Powered-By
* set-cookie: [cookie](##expected-cookie)

### Payload
* description : [String]
#### Example
``` 
{
    "description": "OK"
}
```
## Expected Cookie
* name: cookie.sid
* value: [token string]
* Domain
* Path: /
* Expires
* Http: true
* Secure: false (for now)
### Example 
```
Name: 'cookie.sid'
value: 's%3ABqmbP0EzsabU9ZThFNB3wRQ6rt4eMSYR.9Moujd9o5RKPMJeo2%2Fp0s1GIPauGa1xKvSwBmcWODMU'
Domain: 'localhost'
Path: /
Expires: 'Tue, 11 Sep 2018 13:49:24 GMT'
HttpOnly: true
```
## Used StatusCodes
* 200 - OK
* 400 - BAD_REQUEST
* 401 - UNAUTHORIZED
* 500 - INTERNAL_SERVER_ERROR

## How it works

### First log in
For the first time you must authorize yourself by credentials.

#### Possible responses
* Correct authorization: 200
* Wrong credentials: 401
* Empty payload property : 400
* Missing payload property: 400

### Next log in
After successful login, server serialize your session, and generates session token which works as unique ID to your saved session. Tokens sessions are saved in database. They are removed after expiration date. Same session token, server sends to user as cookie in response.

There are two options to log in at this moment:
*  Via credentials
*  Via cookie

If cookie is attached, then credentials are not necessary.

If cookie will be attached to login request, server automatically detects cookie and checks session token from cookie exists in database. If token exists, server restore user session and send successful response. If token not exists in database, server sends UNAUTHORIZED response.

Server returns unauthorized message when:
* token session isn't fit to any saved token session saved in database
* token session not exists in database, because is removed after expiration date


#### Possible responses
* Correct authorization: 200
* Wrong credentials: 401
* Wrong cookie session token : 401
* Missing cookie and credentials: 400

## Logout
This endpoint **requires** cookie to authorization.  

Server removes token session from database regardless of expiration date. It makes cookie useless.
Also server removes cookie from browser storage.

#### Possible responses
* Correct logout: 200
* Wrong cookie session token : 401
* Missing cookie and credentials: 400
