### ISSUE TITLE
Screen glitch while entering chat directly

### ISSUE THREAD

**Issue by michaelKurowski** [michaelKurowski/lokim2#73]
**List of steps leading to reproduce the error**
- I run server via `npm start`
- I run frontend via `npm start`
- I open `localhost:3000/chat` directly

**Expected result**
I should be shown a chat page, or be redirected if I'm not logged in

**Actual result**
I see glitched page:
![image](https://user-images.githubusercontent.com/2772942/39966218-0932b2f6-56a8-11e8-8254-82d0968c7767.png)

**Logs**
Google Chrome console logs:
[localhost-1526206842189chat.log](https://github.com/michaelKurowski/lokim2/files/1998331/localhost-1526206842189chat.log)

**Comment by Jordan141** [comment]
Fixed that bug, leaving a note for myself to include a fix for the bug that came up. Seems that while redirecting to '/' from '/chat', it attempts to reload '/chat' again, fails, returns to '/', resulting in the component for '/' not loading. This is "fixed" by a page refresh. No additional code prompts other than 
"Cannot redirect to the current route". 

Attempted fixes: 
- Implementing the history package of router, this introduced a bug of it's own where it would return to the previous component without adjusting the URL.

Due to the exponentially increasing complexity of this bug, I will attack it another day. For now, the initial issue that this was opened for, has been fixed in https://github.com/michaelKurowski/lokim2/commit/7ad21c733385d51235301d6680d35fc2a53305e1

**Comment by michaelKurowski** [comment]
@Jordan141 Let's push the PR, for the issue and open another ticket.

**Comment by Jordan141** [comment]
Frontend is too brittle in this branch currently to push to master, let me fix more things.

**Comment by Jordan141** [comment]
With recent commit, page navigation is vastly improved in it's stability. However, it's still not ready to push to master.
